import type { Agent } from "@/types";
import { calculateAgentReadyScore } from "@/lib/scoring";

const now = new Date().toISOString();

function seed(
  agent: Omit<Agent, "agent_ready_score" | "status" | "source" | "created_at" | "updated_at" | "published_at">
): Agent {
  const scoreInput = {
    has_mcp: agent.has_mcp,
    has_api: agent.has_api,
    is_structured: agent.is_structured,
    is_open_source: agent.is_open_source,
    is_self_hostable: agent.is_self_hostable,
    payment_ready: agent.payment_ready,
    docs_url: agent.docs_url,
    rating: agent.rating,
  };
  return {
    ...agent,
    agent_ready_score: calculateAgentReadyScore(scoreInput),
    status: "published",
    source: "seed",
    created_at: now,
    updated_at: now,
    published_at: now,
  };
}

export const ADDITIONAL_DEMO_AGENTS: Agent[] = [
  seed({
    id: "9",
    name: "Playwright MCP",
    slug: "playwright-mcp",
    short_description:
      "Official MCP server for browser automation and web testing via Playwright.",
    description:
      "Microsoft Playwright MCP enables AI agents to control browsers, run automated tests, scrape pages, and interact with web UIs through the Model Context Protocol.",
    website_url: "https://github.com/microsoft/playwright-mcp",
    github_url: "https://github.com/microsoft/playwright-mcp",
    docs_url: "https://playwright.dev",
    mcp_url: "https://github.com/microsoft/playwright-mcp",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 680,
    view_count: 42000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "10",
    name: "GitHub MCP",
    slug: "github-mcp",
    short_description:
      "Official MCP server for GitHub repos, issues, PRs, and code search.",
    description:
      "GitHub MCP Server gives AI agents structured access to repositories, pull requests, issues, and code search.",
    website_url: "https://github.com/github/github-mcp-server",
    github_url: "https://github.com/github/github-mcp-server",
    docs_url:
      "https://docs.github.com/en/copilot/how-tos/context/model-context-protocol",
    mcp_url: "https://github.com/github/github-mcp-server",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 920,
    view_count: 58000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
    ],
  }),
  seed({
    id: "11",
    name: "Supabase MCP",
    slug: "supabase-mcp",
    short_description:
      "MCP server for querying and managing Supabase databases and projects.",
    description:
      "Supabase MCP connects AI agents directly to your Supabase projects for SQL, schema inspection, and data management.",
    website_url: "https://supabase.com",
    github_url: "https://github.com/supabase-community/supabase-mcp",
    docs_url: "https://supabase.com/docs/guides/getting-started/mcp",
    mcp_url: "https://github.com/supabase-community/supabase-mcp",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 540,
    view_count: 36000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
    ],
  }),
  seed({
    id: "12",
    name: "Exa",
    slug: "exa",
    short_description:
      "Neural search API and MCP server for AI-native web research.",
    description:
      "Exa provides semantic web search designed for AI agents with an official MCP server for agent integrations.",
    website_url: "https://exa.ai",
    github_url: "https://github.com/exa-labs/exa-mcp-server",
    docs_url: "https://docs.exa.ai",
    mcp_url: "https://github.com/exa-labs/exa-mcp-server",
    pricing_type: "freemium",
    pricing_details: "Free tier + usage-based pricing",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: true,
    rating: 4.5,
    review_count: 780,
    view_count: 64000,
    categories: [{ id: "2", name: "Research", slug: "research" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "13",
    name: "Tavily",
    slug: "tavily",
    short_description:
      "Search API built for AI agents with real-time web results and MCP support.",
    description:
      "Tavily is a search engine optimized for LLM agents with clean, cited results and an official MCP server.",
    website_url: "https://tavily.com",
    github_url: "https://github.com/tavily-ai/tavily-mcp",
    docs_url: "https://docs.tavily.com",
    mcp_url: "https://github.com/tavily-ai/tavily-mcp",
    pricing_type: "freemium",
    pricing_details: "Free tier + paid plans",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: true,
    rating: 4.4,
    review_count: 650,
    view_count: 52000,
    categories: [{ id: "2", name: "Research", slug: "research" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "14",
    name: "Notion MCP",
    slug: "notion-mcp",
    short_description:
      "Official Notion MCP server for reading and writing workspace content.",
    description:
      "Notion MCP lets AI agents interact with Notion pages, databases, and blocks through an officially supported MCP server.",
    website_url: "https://notion.so",
    docs_url: "https://developers.notion.com/docs/mcp",
    mcp_url: "https://developers.notion.com/docs/mcp",
    pricing_type: "freemium",
    pricing_details: "Included with Notion plans",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.3,
    review_count: 410,
    view_count: 38000,
    categories: [{ id: "4", name: "Content", slug: "content" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "15",
    name: "Browserbase",
    slug: "browserbase",
    short_description:
      "Cloud browser infrastructure with MCP for agent-driven web automation.",
    description:
      "Browserbase provides headless browsers in the cloud for AI agents with MCP support for web navigation and data extraction.",
    website_url: "https://browserbase.com",
    github_url: "https://github.com/browserbase",
    docs_url: "https://docs.browserbase.com",
    mcp_url: "https://github.com/browserbase/mcp-server-browserbase",
    pricing_type: "freemium",
    pricing_details: "Free tier + usage-based",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: true,
    rating: 4.4,
    review_count: 380,
    view_count: 29000,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "16",
    name: "Context7",
    slug: "context7",
    short_description:
      "MCP server for up-to-date library documentation and code examples.",
    description:
      "Context7 resolves library docs on demand so coding agents always use current APIs and reduce outdated code suggestions.",
    website_url: "https://context7.com",
    github_url: "https://github.com/upstash/context7",
    docs_url: "https://context7.com/docs",
    mcp_url: "https://github.com/upstash/context7",
    pricing_type: "freemium",
    pricing_details: "Free tier available",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 520,
    view_count: 44000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "17",
    name: "Flowise",
    slug: "flowise",
    short_description:
      "Open-source visual builder for AI agents with MCP server support.",
    description:
      "Flowise is a low-code platform for building LLM flows and agent chains with RAG, tool calling, and MCP integrations.",
    website_url: "https://flowiseai.com",
    github_url: "https://github.com/FlowiseAI/Flowise",
    docs_url: "https://docs.flowiseai.com",
    mcp_url: "https://docs.flowiseai.com/tutorials/mcp",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.4,
    review_count: 870,
    view_count: 72000,
    categories: [{ id: "6", name: "Multi-Agent", slug: "multi-agent" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "18",
    name: "Cline",
    slug: "cline",
    short_description:
      "Autonomous coding agent for VS Code with tool use and MCP client support.",
    description:
      "Cline is an AI coding assistant in VS Code that edits files, runs commands, and connects to MCP servers for extended capabilities.",
    website_url: "https://cline.bot",
    github_url: "https://github.com/cline/cline",
    docs_url: "https://docs.cline.bot",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: false,
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 1240,
    view_count: 95000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "19",
    name: "Aider",
    slug: "aider",
    short_description:
      "Terminal pair programmer that edits code in your local git repo.",
    description:
      "Aider is a command-line AI coding tool with git integration and whole-codebase context for fast iterative development.",
    website_url: "https://aider.chat",
    github_url: "https://github.com/Aider-AI/aider",
    docs_url: "https://aider.chat/docs/",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: false,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 1890,
    view_count: 112000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "20",
    name: "OpenHands",
    slug: "openhands",
    short_description:
      "Open-source platform for autonomous software development agents.",
    description:
      "OpenHands is a community-driven platform where AI agents write code, run commands, browse the web, and collaborate on dev tasks.",
    website_url: "https://openhands.dev",
    github_url: "https://github.com/OpenHands/OpenHands",
    docs_url: "https://docs.openhands.dev",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: false,
    is_structured: true,
    payment_ready: false,
    rating: 4.4,
    review_count: 960,
    view_count: 68000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "21",
    name: "AutoGen",
    slug: "autogen",
    short_description:
      "Microsoft framework for building multi-agent conversational AI systems.",
    description:
      "AutoGen enables multiple AI agents to collaborate through structured conversations with tool use and human-in-the-loop patterns.",
    website_url: "https://microsoft.github.io/autogen/",
    github_url: "https://github.com/microsoft/autogen",
    docs_url: "https://microsoft.github.io/autogen/stable/",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: false,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 1340,
    view_count: 98000,
    categories: [{ id: "6", name: "Multi-Agent", slug: "multi-agent" }],
    tags: [
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "22",
    name: "LlamaIndex",
    slug: "llamaindex",
    short_description:
      "Data framework for LLM apps with RAG, agents, and MCP tool integrations.",
    description:
      "LlamaIndex connects LLMs to your data with ingestion, indexing, retrieval pipelines, and MCP servers for production RAG.",
    website_url: "https://www.llamaindex.ai",
    github_url: "https://github.com/run-llama/llama_index",
    docs_url: "https://docs.llamaindex.ai",
    mcp_url: "https://github.com/run-llama/llamaindex-mcp",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 1100,
    view_count: 85000,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "23",
    name: "Dify",
    slug: "dify",
    short_description:
      "Open-source LLM app platform with agents, workflows, and MCP support.",
    description:
      "Dify is a production-ready platform for building AI apps and agents with visual workflows, RAG, and MCP tool integrations.",
    website_url: "https://dify.ai",
    github_url: "https://github.com/langgenius/dify",
    docs_url: "https://docs.dify.ai",
    mcp_url: "https://docs.dify.ai/guides/tools/mcp",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0 + cloud",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 1420,
    view_count: 105000,
    categories: [{ id: "6", name: "Multi-Agent", slug: "multi-agent" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
];
