import type { Agent } from "@/types";
import { calculateAgentReadyScore } from "@/lib/scoring";

const now = new Date().toISOString();

function seed(
  agent: Omit<Agent, "agent_ready_score" | "status" | "source" | "created_at" | "updated_at" | "published_at">
): Agent {
  const scoreInput = {
    has_mcp: agent.has_mcp,
    has_api: agent.has_api,
    is_structured: agent.is_structured,
    is_open_source: agent.is_open_source,
    is_self_hostable: agent.is_self_hostable,
    payment_ready: agent.payment_ready,
    docs_url: agent.docs_url,
    rating: agent.rating,
  };
  return {
    ...agent,
    agent_ready_score: calculateAgentReadyScore(scoreInput),
    status: "published",
    source: "seed",
    created_at: now,
    updated_at: now,
    published_at: now,
  };
}

export const ADDITIONAL_DEMO_AGENTS: Agent[] = [
  seed({
    id: "9",
    name: "Playwright MCP",
    slug: "playwright-mcp",
    short_description:
      "Official MCP server for browser automation and web testing via Playwright.",
    description:
      "Microsoft Playwright MCP enables AI agents to control browsers, run automated tests, scrape pages, and interact with web UIs through the Model Context Protocol.",
    website_url: "https://github.com/microsoft/playwright-mcp",
    github_url: "https://github.com/microsoft/playwright-mcp",
    docs_url: "https://playwright.dev",
    mcp_url: "https://github.com/microsoft/playwright-mcp",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 680,
    view_count: 42000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "10",
    name: "GitHub MCP",
    slug: "github-mcp",
    short_description:
      "Official MCP server for GitHub repos, issues, PRs, and code search.",
    description:
      "GitHub MCP Server gives AI agents structured access to repositories, pull requests, issues, and code search.",
    website_url: "https://github.com/github/github-mcp-server",
    github_url: "https://github.com/github/github-mcp-server",
    docs_url:
      "https://docs.github.com/en/copilot/how-tos/context/model-context-protocol",
    mcp_url: "https://github.com/github/github-mcp-server",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 920,
    view_count: 58000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
    ],
  }),
  seed({
    id: "11",
    name: "Supabase MCP",
    slug: "supabase-mcp",
    short_description:
      "MCP server for querying and managing Supabase databases and projects.",
    description:
      "Supabase MCP connects AI agents directly to your Supabase projects for SQL, schema inspection, and data management.",
    website_url: "https://supabase.com",
    github_url: "https://github.com/supabase-community/supabase-mcp",
    docs_url: "https://supabase.com/docs/guides/getting-started/mcp",
    mcp_url: "https://github.com/supabase-community/supabase-mcp",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 540,
    view_count: 36000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
    ],
  }),
  seed({
    id: "12",
    name: "Exa",
    slug: "exa",
    short_description:
      "Neural search API and MCP server for AI-native web research.",
    description:
      "Exa provides semantic web search designed for AI agents with an official MCP server for agent integrations.",
    website_url: "https://exa.ai",
    github_url: "https://github.com/exa-labs/exa-mcp-server",
    docs_url: "https://docs.exa.ai",
    mcp_url: "https://github.com/exa-labs/exa-mcp-server",
    pricing_type: "freemium",
    pricing_details: "Free tier + usage-based pricing",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: true,
    rating: 4.5,
    review_count: 780,
    view_count: 64000,
    categories: [{ id: "2", name: "Research", slug: "research" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "13",
    name: "Tavily",
    slug: "tavily",
    short_description:
      "Search API built for AI agents with real-time web results and MCP support.",
    description:
      "Tavily is a search engine optimized for LLM agents with clean, cited results and an official MCP server.",
    website_url: "https://tavily.com",
    github_url: "https://github.com/tavily-ai/tavily-mcp",
    docs_url: "https://docs.tavily.com",
    mcp_url: "https://github.com/tavily-ai/tavily-mcp",
    pricing_type: "freemium",
    pricing_details: "Free tier + paid plans",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: true,
    rating: 4.4,
    review_count: 650,
    view_count: 52000,
    categories: [{ id: "2", name: "Research", slug: "research" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "14",
    name: "Notion MCP",
    slug: "notion-mcp",
    short_description:
      "Official Notion MCP server for reading and writing workspace content.",
    description:
      "Notion MCP lets AI agents interact with Notion pages, databases, and blocks through an officially supported MCP server.",
    website_url: "https://notion.so",
    docs_url: "https://developers.notion.com/docs/mcp",
    mcp_url: "https://developers.notion.com/docs/mcp",
    pricing_type: "freemium",
    pricing_details: "Included with Notion plans",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.3,
    review_count: 410,
    view_count: 38000,
    categories: [{ id: "4", name: "Content", slug: "content" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "15",
    name: "Browserbase",
    slug: "browserbase",
    short_description:
      "Cloud browser infrastructure with MCP for agent-driven web automation.",
    description:
      "Browserbase provides headless browsers in the cloud for AI agents with MCP support for web navigation and data extraction.",
    website_url: "https://browserbase.com",
    github_url: "https://github.com/browserbase",
    docs_url: "https://docs.browserbase.com",
    mcp_url: "https://github.com/browserbase/mcp-server-browserbase",
    pricing_type: "freemium",
    pricing_details: "Free tier + usage-based",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: true,
    rating: 4.4,
    review_count: 380,
    view_count: 29000,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "16",
    name: "Context7",
    slug: "context7",
    short_description:
      "MCP server for up-to-date library documentation and code examples.",
    description:
      "Context7 resolves library docs on demand so coding agents always use current APIs and reduce outdated code suggestions.",
    website_url: "https://context7.com",
    github_url: "https://github.com/upstash/context7",
    docs_url: "https://context7.com/docs",
    mcp_url: "https://github.com/upstash/context7",
    pricing_type: "freemium",
    pricing_details: "Free tier available",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 520,
    view_count: 44000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "17",
    name: "Flowise",
    slug: "flowise",
    short_description:
      "Open-source visual builder for AI agents with MCP server support.",
    description:
      "Flowise is a low-code platform for building LLM flows and agent chains with RAG, tool calling, and MCP integrations.",
    website_url: "https://flowiseai.com",
    github_url: "https://github.com/FlowiseAI/Flowise",
    docs_url: "https://docs.flowiseai.com",
    mcp_url: "https://docs.flowiseai.com/tutorials/mcp",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.4,
    review_count: 870,
    view_count: 72000,
    categories: [{ id: "6", name: "Multi-Agent", slug: "multi-agent" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "18",
    name: "Cline",
    slug: "cline",
    short_description:
      "Autonomous coding agent for VS Code with tool use and MCP client support.",
    description:
      "Cline is an AI coding assistant in VS Code that edits files, runs commands, and connects to MCP servers for extended capabilities.",
    website_url: "https://cline.bot",
    github_url: "https://github.com/cline/cline",
    docs_url: "https://docs.cline.bot",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: false,
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 1240,
    view_count: 95000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "19",
    name: "Aider",
    slug: "aider",
    short_description:
      "Terminal pair programmer that edits code in your local git repo.",
    description:
      "Aider is a command-line AI coding tool with git integration and whole-codebase context for fast iterative development.",
    website_url: "https://aider.chat",
    github_url: "https://github.com/Aider-AI/aider",
    docs_url: "https://aider.chat/docs/",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: false,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 1890,
    view_count: 112000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "20",
    name: "OpenHands",
    slug: "openhands",
    short_description:
      "Open-source platform for autonomous software development agents.",
    description:
      "OpenHands is a community-driven platform where AI agents write code, run commands, browse the web, and collaborate on dev tasks.",
    website_url: "https://openhands.dev",
    github_url: "https://github.com/OpenHands/OpenHands",
    docs_url: "https://docs.openhands.dev",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: false,
    is_structured: true,
    payment_ready: false,
    rating: 4.4,
    review_count: 960,
    view_count: 68000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "21",
    name: "AutoGen",
    slug: "autogen",
    short_description:
      "Microsoft framework for building multi-agent conversational AI systems.",
    description:
      "AutoGen enables multiple AI agents to collaborate through structured conversations with tool use and human-in-the-loop patterns.",
    website_url: "https://microsoft.github.io/autogen/",
    github_url: "https://github.com/microsoft/autogen",
    docs_url: "https://microsoft.github.io/autogen/stable/",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: false,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 1340,
    view_count: 98000,
    categories: [{ id: "6", name: "Multi-Agent", slug: "multi-agent" }],
    tags: [
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "22",
    name: "LlamaIndex",
    slug: "llamaindex",
    short_description:
      "Data framework for LLM apps with RAG, agents, and MCP tool integrations.",
    description:
      "LlamaIndex connects LLMs to your data with ingestion, indexing, retrieval pipelines, and MCP servers for production RAG.",
    website_url: "https://www.llamaindex.ai",
    github_url: "https://github.com/run-llama/llama_index",
    docs_url: "https://docs.llamaindex.ai",
    mcp_url: "https://github.com/run-llama/llamaindex-mcp",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 1100,
    view_count: 85000,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  // ---------- agents in seed.sql not yet in demo data ----------
  seed({
    id: "24",
    name: "n8n AI Agent",
    slug: "n8n-ai-agent",
    short_description:
      "Workflow automation with built-in AI agent nodes and tool calling.",
    description:
      "n8n combines workflow automation with AI agent capabilities. Build agents that call APIs, process data, and automate business processes with a visual editor. Self-hostable with a fair-code license.",
    website_url: "https://n8n.io",
    github_url: "https://github.com/n8n-io/n8n",
    docs_url: "https://docs.n8n.io",
    pricing_type: "open_source",
    pricing_details: "Fair-code license",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: false,
    is_structured: true,
    payment_ready: false,
    rating: 4.3,
    review_count: 760,
    view_count: 45000,
    categories: [{ id: "6", name: "Multi-Agent", slug: "multi-agent" }],
    tags: [
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "25",
    name: "AutoGPT",
    slug: "autogpt",
    short_description:
      "Pioneer autonomous agent framework for goal-driven task execution.",
    description:
      "AutoGPT was one of the first open-source autonomous AI agents. It breaks down goals into sub-tasks and executes them using tools and APIs autonomously.",
    website_url: "https://agpt.co",
    github_url: "https://github.com/Significant-Gravitas/AutoGPT",
    docs_url: "https://docs.agpt.co",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: false,
    is_structured: false,
    payment_ready: false,
    rating: 3.9,
    review_count: 2100,
    view_count: 156000,
    categories: [{ id: "6", name: "Multi-Agent", slug: "multi-agent" }],
    tags: [
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  // ---------- new agents ----------
  seed({
    id: "26",
    name: "Stripe Agent Toolkit",
    slug: "stripe-agent-toolkit",
    short_description:
      "Official Stripe MCP server for payments, customers, and subscriptions.",
    description:
      "Stripe Agent Toolkit gives AI agents secure access to the Stripe API via MCP. Supports creating payment links, managing customers, querying charges, and triggering refunds.",
    website_url: "https://stripe.com",
    github_url: "https://github.com/stripe/agent-toolkit",
    docs_url: "https://docs.stripe.com/agents",
    mcp_url: "https://github.com/stripe/agent-toolkit",
    pricing_type: "freemium",
    pricing_details: "Free to use; Stripe fees apply",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: true,
    rating: 4.4,
    review_count: 310,
    view_count: 28000,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "27",
    name: "Cloudflare MCP",
    slug: "cloudflare-mcp",
    short_description:
      "Official MCP server for Cloudflare Workers, KV, D1, and AI Gateway.",
    description:
      "Cloudflare MCP Server lets AI agents interact with your Cloudflare account: deploy Workers, read KV stores, query D1 databases, and manage AI Gateway configs.",
    website_url: "https://cloudflare.com",
    github_url: "https://github.com/cloudflare/mcp-server-cloudflare",
    docs_url: "https://developers.cloudflare.com/mcp",
    mcp_url: "https://github.com/cloudflare/mcp-server-cloudflare",
    pricing_type: "freemium",
    pricing_details: "Cloudflare free tier + Workers pricing",
    is_open_source: true,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.4,
    review_count: 280,
    view_count: 24000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "28",
    name: "Brave Search MCP",
    slug: "brave-search-mcp",
    short_description:
      "MCP server for privacy-first web and local search via Brave Search API.",
    description:
      "Brave Search MCP is an official reference server from Anthropic that provides web search and local search results to AI agents using the Brave Search API.",
    website_url: "https://brave.com/search/api/",
    github_url: "https://github.com/modelcontextprotocol/servers",
    docs_url: "https://api.search.brave.com/app/documentation/web-search/get-started",
    mcp_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
    pricing_type: "freemium",
    pricing_details: "2,000 free queries/mo; paid plans from $3/1k queries",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.3,
    review_count: 240,
    view_count: 21000,
    categories: [{ id: "2", name: "Research", slug: "research" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "29",
    name: "Sentry MCP",
    slug: "sentry-mcp",
    short_description:
      "Official MCP server for querying Sentry errors, issues, and traces.",
    description:
      "Sentry MCP lets AI agents inspect error events, search issues, read stack traces, and surface performance problems directly from your Sentry projects.",
    website_url: "https://sentry.io",
    github_url: "https://github.com/getsentry/sentry-mcp",
    docs_url: "https://docs.sentry.io/product/sentry-mcp/",
    mcp_url: "https://github.com/getsentry/sentry-mcp",
    pricing_type: "freemium",
    pricing_details: "Requires Sentry account; free developer plan available",
    is_open_source: true,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.4,
    review_count: 195,
    view_count: 18000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "30",
    name: "Pydantic AI",
    slug: "pydantic-ai",
    short_description:
      "Python agent framework with type-safe tool use and MCP client support.",
    description:
      "Pydantic AI is a production-grade Python framework for building AI agents with structured outputs, dependency injection, type-safe tool schemas, and native MCP client integration.",
    website_url: "https://ai.pydantic.dev",
    github_url: "https://github.com/pydantic/pydantic-ai",
    docs_url: "https://ai.pydantic.dev/docs/",
    mcp_url: "https://ai.pydantic.dev/docs/mcp/",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 480,
    view_count: 38000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "31",
    name: "Sequential Thinking MCP",
    slug: "sequential-thinking-mcp",
    short_description:
      "MCP server for structured multi-step reasoning and problem decomposition.",
    description:
      "Sequential Thinking MCP is an official reference server that provides agents with a structured tool for breaking complex problems into explicit reasoning steps before acting.",
    website_url: "https://github.com/modelcontextprotocol/servers",
    github_url: "https://github.com/modelcontextprotocol/servers",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    mcp_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.3,
    review_count: 170,
    view_count: 16000,
    categories: [{ id: "2", name: "Research", slug: "research" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "32",
    name: "Windsurf",
    slug: "windsurf",
    short_description:
      "AI-native code editor by Codeium with agentic flows and MCP support.",
    description:
      "Windsurf is an AI-first code editor from Codeium featuring Cascade, a deeply integrated agent that edits code, runs commands, and connects to MCP servers for extended tool access.",
    website_url: "https://codeium.com/windsurf",
    docs_url: "https://docs.codeium.com/windsurf",
    mcp_url: "https://docs.codeium.com/windsurf/mcp",
    pricing_type: "freemium",
    pricing_details: "Free tier + Pro from $15/mo",
    is_open_source: false,
    is_self_hostable: false,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 890,
    view_count: 62000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [{ id: "1", name: "MCP", slug: "mcp" }],
  }),
  seed({
    id: "33",
    name: "Semantic Kernel",
    slug: "semantic-kernel",
    short_description:
      "Microsoft SDK for building AI agents with plugins, memory, and MCP.",
    description:
      "Semantic Kernel is Microsoft's open-source SDK for integrating LLMs into .NET, Python, and Java apps. Supports function calling, MCP servers, planners, and memory for production agents.",
    website_url: "https://learn.microsoft.com/en-us/semantic-kernel/overview/",
    github_url: "https://github.com/microsoft/semantic-kernel",
    docs_url: "https://learn.microsoft.com/en-us/semantic-kernel/",
    mcp_url: "https://devblogs.microsoft.com/semantic-kernel/model-context-protocol-and-semantic-kernel/",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.4,
    review_count: 720,
    view_count: 54000,
    categories: [{ id: "6", name: "Multi-Agent", slug: "multi-agent" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  // ---------- official Anthropic reference servers ----------
  seed({
    id: "34",
    name: "Filesystem MCP",
    slug: "filesystem-mcp",
    short_description:
      "Official MCP server for secure local filesystem read and write access.",
    description:
      "Filesystem MCP is an official Anthropic reference server that gives AI agents structured access to local directories: read files, list paths, search, and write with configurable permissions.",
    website_url: "https://github.com/modelcontextprotocol/servers",
    github_url: "https://github.com/modelcontextprotocol/servers",
    docs_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    mcp_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 890,
    view_count: 74000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "35",
    name: "Memory MCP",
    slug: "memory-mcp",
    short_description:
      "Official MCP server for persistent agent memory via a knowledge graph.",
    description:
      "Memory MCP is an official Anthropic reference server that stores and retrieves entities, relations, and observations across sessions — giving agents durable long-term memory.",
    website_url: "https://github.com/modelcontextprotocol/servers",
    github_url: "https://github.com/modelcontextprotocol/servers",
    docs_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    mcp_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 620,
    view_count: 52000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "36",
    name: "PostgreSQL MCP",
    slug: "postgres-mcp",
    short_description:
      "Official MCP server for read-only SQL queries against a Postgres database.",
    description:
      "PostgreSQL MCP is an official Anthropic reference server that lets AI agents run read-only SQL, inspect schemas, and describe tables in any accessible Postgres database.",
    website_url: "https://github.com/modelcontextprotocol/servers",
    github_url: "https://github.com/modelcontextprotocol/servers",
    docs_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
    mcp_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 680,
    view_count: 55000,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "37",
    name: "Slack MCP",
    slug: "slack-mcp",
    short_description:
      "Official MCP server for reading Slack channels and posting messages.",
    description:
      "Slack MCP is an official Anthropic reference server that gives AI agents access to Slack workspaces: list channels, read history, and post messages via the Slack API.",
    website_url: "https://slack.com",
    github_url: "https://github.com/modelcontextprotocol/servers",
    docs_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
    mcp_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
    pricing_type: "freemium",
    pricing_details: "Free Slack plan supported",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.3,
    review_count: 420,
    view_count: 36000,
    categories: [{ id: "4", name: "Content", slug: "content" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "38",
    name: "Google Drive MCP",
    slug: "gdrive-mcp",
    short_description:
      "Official MCP server for searching and reading Google Drive files.",
    description:
      "Google Drive MCP is an official Anthropic reference server that lets AI agents search Drive, list files, and read document contents including Google Docs and Sheets.",
    website_url: "https://workspace.google.com",
    github_url: "https://github.com/modelcontextprotocol/servers",
    docs_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive",
    mcp_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive",
    pricing_type: "freemium",
    pricing_details: "Requires Google Workspace or personal account",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.3,
    review_count: 380,
    view_count: 33000,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "39",
    name: "Puppeteer MCP",
    slug: "puppeteer-mcp",
    short_description:
      "Official MCP server for browser automation via CDP and screenshots.",
    description:
      "Puppeteer MCP is an official Anthropic reference server for browser automation. Unlike Playwright MCP it uses screenshot-based vision rather than accessibility tree, suiting visual tasks.",
    website_url: "https://github.com/modelcontextprotocol/servers",
    github_url: "https://github.com/modelcontextprotocol/servers",
    docs_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
    mcp_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.3,
    review_count: 340,
    view_count: 29000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "40",
    name: "Fetch MCP",
    slug: "fetch-mcp",
    short_description:
      "Official MCP server for fetching URLs and converting pages to Markdown.",
    description:
      "Fetch MCP is an official Anthropic reference server that converts any URL to clean, LLM-friendly Markdown or raw text, with support for extracting specific content via CSS selectors.",
    website_url: "https://github.com/modelcontextprotocol/servers",
    github_url: "https://github.com/modelcontextprotocol/servers",
    docs_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    mcp_url:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 710,
    view_count: 60000,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  // ---------- third-party MCP servers ----------
  seed({
    id: "41",
    name: "Linear MCP",
    slug: "linear-mcp",
    short_description:
      "Official Linear MCP server for issues, projects, and team workflows.",
    description:
      "Linear MCP gives AI agents access to your Linear workspace: create and update issues, search projects, read cycle state, and manage team workflows through Linear's native MCP server.",
    website_url: "https://linear.app",
    docs_url: "https://linear.app/docs/mcp",
    mcp_url: "https://linear.app/docs/mcp",
    pricing_type: "freemium",
    pricing_details: "Requires Linear account; free plan available",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 390,
    view_count: 35000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "42",
    name: "JetBrains MCP",
    slug: "jetbrains-mcp",
    short_description:
      "Official MCP proxy for IntelliJ-based IDEs — expose IDE actions to agents.",
    description:
      "JetBrains MCP Proxy runs alongside any IntelliJ IDE and exposes editor actions, project structure, open files, and refactoring tools to external AI agents via the MCP protocol.",
    website_url: "https://www.jetbrains.com",
    github_url: "https://github.com/JetBrains/mcp-jetbrains",
    docs_url: "https://github.com/JetBrains/mcp-jetbrains",
    mcp_url: "https://github.com/JetBrains/mcp-jetbrains",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.3,
    review_count: 310,
    view_count: 27000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  // ---------- agent frameworks / coding agents ----------
  seed({
    id: "43",
    name: "Continue",
    slug: "continue",
    short_description:
      "Open-source AI coding assistant for VS Code and JetBrains with MCP client.",
    description:
      "Continue is an open-source AI pair programmer that works inside VS Code and JetBrains IDEs. Supports custom models, context providers, slash commands, and MCP servers for tool use.",
    website_url: "https://continue.dev",
    github_url: "https://github.com/continuedev/continue",
    docs_url: "https://docs.continue.dev",
    mcp_url: "https://docs.continue.dev/customize/context-providers/mcp",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 1080,
    view_count: 88000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "44",
    name: "Haystack",
    slug: "haystack",
    short_description:
      "Open-source Python framework for RAG pipelines, agents, and MCP tools.",
    description:
      "Haystack by deepset is a production-ready framework for building LLM apps with retrieval-augmented generation, agent pipelines, tool calling, and MCP server integrations.",
    website_url: "https://haystack.deepset.ai",
    github_url: "https://github.com/deepset-ai/haystack",
    docs_url: "https://docs.haystack.deepset.ai",
    mcp_url: "https://docs.haystack.deepset.ai/docs/mcptool",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.4,
    review_count: 740,
    view_count: 62000,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "45",
    name: "Roo Code",
    slug: "roo-code",
    short_description:
      "Autonomous VS Code coding agent with MCP support and multi-model switching.",
    description:
      "Roo Code is an open-source agentic coding extension for VS Code. Edits files, runs terminal commands, connects to MCP servers, and supports fast model switching for different task types.",
    website_url: "https://roocode.com",
    github_url: "https://github.com/RooVetGit/Roo-Code",
    docs_url: "https://docs.roocode.com",
    mcp_url: "https://docs.roocode.com/features/mcp",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 640,
    view_count: 53000,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "46",
    name: "Grafana MCP",
    slug: "grafana-mcp",
    short_description:
      "Official MCP server for Grafana dashboards, datasources, alerting, and incidents.",
    description:
      "Grafana MCP gives AI agents structured access to dashboards, Prometheus and Loki queries, alerting, OnCall, and incidents on Grafana Cloud or self-managed Grafana.",
    website_url: "https://grafana.com",
    github_url: "https://github.com/grafana/mcp-grafana",
    docs_url: "https://grafana.com/docs/grafana/latest/developer-resources/mcp/",
    mcp_url: "https://github.com/grafana/mcp-grafana",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    kind: "mcp",
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 410,
    view_count: 28000,
    last_verified_at: now,
    categories: [{ id: "7", name: "Observability", slug: "observability" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "47",
    name: "Chrome DevTools MCP",
    slug: "chrome-devtools-mcp",
    short_description:
      "Official Chrome DevTools MCP for browser automation, debugging, and performance traces.",
    description:
      "Chrome DevTools MCP lets coding agents control a live Chrome browser, inspect the console and network, take screenshots, and record performance traces via DevTools.",
    website_url: "https://developer.chrome.com/blog/chrome-devtools-mcp",
    github_url: "https://github.com/ChromeDevTools/chrome-devtools-mcp",
    docs_url: "https://github.com/ChromeDevTools/chrome-devtools-mcp",
    mcp_url: "https://github.com/ChromeDevTools/chrome-devtools-mcp",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    kind: "mcp",
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 890,
    view_count: 51000,
    last_verified_at: now,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "48",
    name: "MongoDB MCP",
    slug: "mongodb-mcp",
    short_description:
      "Official MCP server for querying MongoDB data and managing Atlas deployments.",
    description:
      "MongoDB MCP Server lets AI clients inspect schemas, run queries, manage indexes, and administer Atlas clusters from natural language.",
    website_url: "https://www.mongodb.com",
    github_url: "https://github.com/mongodb-js/mongodb-mcp-server",
    docs_url: "https://www.mongodb.com/docs/mcp-server/",
    mcp_url: "https://github.com/mongodb-js/mongodb-mcp-server",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    kind: "mcp",
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 520,
    view_count: 34000,
    last_verified_at: now,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "49",
    name: "Neon MCP",
    slug: "neon-mcp",
    short_description:
      "Official Neon MCP for Postgres projects, branches, SQL, and schema migrations.",
    description:
      "Neon MCP lets agents create projects, manage branches, run SQL, and apply schema migrations on serverless Postgres via the Neon API or a hosted MCP endpoint.",
    website_url: "https://neon.tech",
    github_url: "https://github.com/neondatabase/mcp-server-neon",
    docs_url: "https://neon.com/docs/ai/neon-mcp-server",
    mcp_url: "https://mcp.neon.tech",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    kind: "mcp",
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 380,
    view_count: 26000,
    last_verified_at: now,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "50",
    name: "Apify MCP",
    slug: "apify-mcp",
    short_description:
      "Official Apify MCP for running Store Actors, crawlers, and web data extraction.",
    description:
      "Apify MCP connects agents to thousands of scrapers and automation Actors on Apify Store, plus platform docs and run results, via hosted MCP or a local stdio server.",
    website_url: "https://apify.com",
    github_url: "https://github.com/apify/apify-mcp-server",
    docs_url: "https://docs.apify.com/platform/integrations/mcp",
    mcp_url: "https://mcp.apify.com",
    pricing_type: "freemium",
    pricing_details: "Hosted MCP plus Apify Store Actors",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    kind: "mcp",
    is_structured: true,
    payment_ready: true,
    rating: 4.4,
    review_count: 460,
    view_count: 31000,
    last_verified_at: now,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "51",
    name: "Blender MCP",
    slug: "blender-mcp",
    short_description:
      "Community MCP server that lets agents control Blender for 3D scenes and modeling.",
    description:
      "Blender MCP (ahujasid) connects an LLM to a Blender addon so agents can create, inspect, and edit 3D scenes through the Model Context Protocol.",
    website_url: "https://github.com/ahujasid/blender-mcp",
    github_url: "https://github.com/ahujasid/blender-mcp",
    docs_url: "https://github.com/ahujasid/blender-mcp",
    mcp_url: "https://github.com/ahujasid/blender-mcp",
    pricing_type: "open_source",
    pricing_details: "MIT License",
    is_open_source: true,
    is_self_hostable: true,
    has_api: false,
    has_mcp: true,
    kind: "mcp",
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 720,
    view_count: 44000,
    last_verified_at: now,
    categories: [{ id: "4", name: "Content", slug: "content" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
    ],
  }),
  seed({
    id: "52",
    name: "Google MCP Toolbox for Databases",
    slug: "google-db-toolbox-mcp",
    short_description:
      "Open-source MCP server from Google for connecting agents to enterprise databases.",
    description:
      "MCP Toolbox for Databases (googleapis) is a production MCP server with prebuilt tools for Postgres, MySQL, BigQuery, AlloyDB, and other databases, including connection pooling and auth.",
    website_url: "https://mcp-toolbox.dev",
    github_url: "https://github.com/googleapis/mcp-toolbox",
    docs_url: "https://mcp-toolbox.dev",
    mcp_url: "https://github.com/googleapis/mcp-toolbox",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    kind: "mcp",
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 340,
    view_count: 22000,
    last_verified_at: now,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "53",
    name: "AWS MCP",
    slug: "aws-mcp",
    short_description:
      "Official suite of AWS MCP servers for docs, CDK, Lambda, cost, and more.",
    description:
      "AWS MCP Servers (awslabs) is an open-source collection of specialized MCP servers that help agents search AWS documentation, generate CDK, invoke Lambda, and analyze cost.",
    website_url: "https://awslabs.github.io/mcp",
    github_url: "https://github.com/awslabs/mcp",
    docs_url: "https://awslabs.github.io/mcp",
    mcp_url: "https://github.com/awslabs/mcp",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    kind: "mcp",
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 610,
    view_count: 39000,
    last_verified_at: now,
    categories: [{ id: "5", name: "Data", slug: "data" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
  seed({
    id: "54",
    name: "Grok",
    slug: "grok",
    short_description:
      "xAI assistant for reasoning, coding, research, and real-time X/web context.",
    description:
      "Grok is xAI’s agentic assistant. It works in chat, Grok.com, and the xAI API, can use tools and remote MCP servers, and is strong at coding and current-events research.",
    website_url: "https://grok.x.ai",
    demo_url: "https://grok.x.ai",
    docs_url: "https://docs.x.ai",
    pricing_type: "freemium",
    pricing_details: "Free + SuperGrok / API",
    is_open_source: false,
    is_self_hostable: false,
    has_api: true,
    has_mcp: false,
    kind: "agent",
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 2100,
    view_count: 180000,
    last_verified_at: now,
    categories: [
      { id: "2", name: "Research", slug: "research" },
      { id: "1", name: "Coding", slug: "coding" },
    ],
    tags: [{ id: "4", name: "API", slug: "api" }],
  }),
  seed({
    id: "55",
    name: "xAI Docs MCP",
    slug: "xai-docs-mcp",
    short_description: "Official MCP server for xAI documentation.",
    description:
      "Hosted MCP endpoint that lets agents query xAI docs instead of pasting pages into context.",
    website_url: "https://docs.x.ai/developers/docs-mcp",
    docs_url: "https://docs.x.ai/developers/docs-mcp",
    mcp_url: "https://docs.x.ai/api/mcp",
    pricing_type: "free",
    pricing_details: "Free",
    is_open_source: false,
    is_self_hostable: false,
    has_api: false,
    has_mcp: true,
    kind: "mcp",
    is_structured: true,
    payment_ready: false,
    rating: 4.5,
    review_count: 120,
    view_count: 9000,
    last_verified_at: now,
    categories: [{ id: "1", name: "Coding", slug: "coding" }],
    tags: [{ id: "1", name: "MCP", slug: "mcp" }],
  }),
  // ---------- Dify (keep last) ----------
  seed({
    id: "23",
    name: "Dify",
    slug: "dify",
    short_description:
      "Open-source LLM app platform with agents, workflows, and MCP support.",
    description:
      "Dify is a production-ready platform for building AI apps and agents with visual workflows, RAG, and MCP tool integrations.",
    website_url: "https://dify.ai",
    github_url: "https://github.com/langgenius/dify",
    docs_url: "https://docs.dify.ai",
    mcp_url: "https://docs.dify.ai/guides/tools/mcp",
    pricing_type: "open_source",
    pricing_details: "Apache 2.0 + cloud",
    is_open_source: true,
    is_self_hostable: true,
    has_api: true,
    has_mcp: true,
    is_structured: true,
    payment_ready: false,
    rating: 4.6,
    review_count: 1420,
    view_count: 105000,
    categories: [{ id: "6", name: "Multi-Agent", slug: "multi-agent" }],
    tags: [
      { id: "1", name: "MCP", slug: "mcp" },
      { id: "2", name: "Open Source", slug: "open-source" },
      { id: "3", name: "Self-Hostable", slug: "self-hostable" },
      { id: "4", name: "API", slug: "api" },
    ],
  }),
];
